const pool = require('./db');

let schemaPromise;

function ensureSchema() {
  if (!schemaPromise) {
    schemaPromise = pool.query(`
      CREATE TABLE IF NOT EXISTS clientes (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nome TEXT NOT NULL,
        contato TEXT DEFAULT '',
        email TEXT DEFAULT '',
        cidade TEXT DEFAULT '',
        segmento TEXT DEFAULT 'Residencial',
        observacoes TEXT DEFAULT '',
        created_at TIMESTAMPTZ DEFAULT NOW(),
        updated_at TIMESTAMPTZ DEFAULT NOW()
      );

      CREATE TABLE IF NOT EXISTS transacoes (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tipo TEXT NOT NULL CHECK (tipo IN ('venda', 'compra', 'invest')),
        data DATE NOT NULL,
        cliente_id BIGINT REFERENCES clientes(id) ON DELETE SET NULL,
        qtd NUMERIC(14,2) DEFAULT 0,
        valor NUMERIC(14,2) DEFAULT 0,
        produto TEXT DEFAULT '',
        descricao TEXT DEFAULT '',
        responsavel TEXT DEFAULT '',
        fornecedor TEXT DEFAULT '',
        forma_pagamento TEXT DEFAULT '',
        pago BOOLEAN DEFAULT FALSE,
        cortesia BOOLEAN DEFAULT FALSE,
        comissao BOOLEAN DEFAULT FALSE,
        created_at TIMESTAMPTZ DEFAULT NOW(),
        updated_at TIMESTAMPTZ DEFAULT NOW()
      );

      CREATE TABLE IF NOT EXISTS lotes (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nome TEXT NOT NULL,
        qtd INTEGER NOT NULL CHECK (qtd >= 0),
        data DATE NOT NULL,
        status TEXT DEFAULT 'Ativo',
        created_at TIMESTAMPTZ DEFAULT NOW(),
        updated_at TIMESTAMPTZ DEFAULT NOW()
      );

      CREATE TABLE IF NOT EXISTS oportunidades (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        cliente_id BIGINT REFERENCES clientes(id) ON DELETE SET NULL,
        titulo TEXT NOT NULL,
        valor NUMERIC(14,2) DEFAULT 0,
        etapa TEXT NOT NULL DEFAULT 'lead',
        previsao DATE,
        observacoes TEXT DEFAULT '',
        created_at TIMESTAMPTZ DEFAULT NOW(),
        updated_at TIMESTAMPTZ DEFAULT NOW()
      );

      CREATE TABLE IF NOT EXISTS tarefas (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        titulo TEXT NOT NULL,
        cliente_id BIGINT REFERENCES clientes(id) ON DELETE SET NULL,
        data DATE NOT NULL,
        hora TIME,
        tipo TEXT DEFAULT '',
        concluida BOOLEAN DEFAULT FALSE,
        created_at TIMESTAMPTZ DEFAULT NOW(),
        updated_at TIMESTAMPTZ DEFAULT NOW()
      );

      CREATE INDEX IF NOT EXISTS idx_transacoes_data ON transacoes(data);
      CREATE INDEX IF NOT EXISTS idx_transacoes_cliente ON transacoes(cliente_id);
      CREATE INDEX IF NOT EXISTS idx_oportunidades_cliente ON oportunidades(cliente_id);
      CREATE INDEX IF NOT EXISTS idx_tarefas_data ON tarefas(data);
    `);
  }
  return schemaPromise;
}

module.exports = ensureSchema;
